apiVersion: apps/v1
kind: Deployment
metadata:
  name: openid
spec:
  selector:
    matchLabels:
      app: openid
  template:
    metadata:
      labels:
        app: openid
    spec:
      containers:
      - name: openid
        image: registry.starcatmeow.cn/dongruixuan/catmeow-auth-service/openid:final-k8s-test
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: config
          mountPath: '/app/config'
          readOnly: true
        - name: secretkey
          mountPath: '/app/secret'
          readOnly: false
        env:
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-credential
              key: username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-credential
              key: password
        - name: MONGO_HOST
          value: mongo
      volumes:
      - name: config
        configMap:
          name: configmap.openid.starcatmeow.cn
      - name: secretkey
        secret:
          secretName: secretkeys.openid.starcatmeow.cn
          defaultMode: 256
