apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-pod-service-endpoint
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:serviceaccount:catmeow-auth:default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: read-pod-service-endpoint
subjects:
  - kind: ServiceAccount
    name: default
    namespace: catmeow-auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openid
spec:
  selector:
    matchLabels:
      app: openid
  template:
    metadata:
      labels:
        app: openid
    spec:
      initContainers:
        - name: wait-for-db
          image: groundnuty/k8s-wait-for:v1.3
          imagePullPolicy: Always
          args:
            - "pod"
            - "-lapp=mongo"
      containers:
        - name: openid
          image: registry.starcatmeow.cn/catmeow/catmeow-auth-service/openid:$CI_COMMIT_TAG
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - name: config
              mountPath: "/app/config"
              readOnly: true
            - name: secretkey
              mountPath: "/app/secret"
              readOnly: false
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-credential
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-credential
                  key: password
            - name: MONGO_HOST
              value: mongo-0.mongo,mongo-1.mongo,mongo-2.mongo
      volumes:
        - name: config
          configMap:
            name: configmap.openid.starcatmeow.cn
        - name: secretkey
          secret:
            secretName: secretkeys.openid.starcatmeow.cn
            defaultMode: 256
---
apiVersion: v1
kind: Service
metadata:
  name: openid
spec:
  selector:
    app: openid
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: openid
  labels:
    name: openid
spec:
  rules:
    - host: openid.starcatmeow.cn
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              serviceName: openid
              servicePort: 80
