apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-pod-service-endpoint
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:serviceaccount:catmeow-auth:default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: read-pod-service-endpoint
subjects:
  - kind: ServiceAccount
    name: default
    namespace: catmeow-auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usercenter-backend
spec:
  selector:
    matchLabels:
      app: usercenter-backend
  template:
    metadata:
      labels:
        app: usercenter-backend
    spec:
      initContainers:
        - name: wait-for-db
          image: groundnuty/k8s-wait-for:v1.3
          imagePullPolicy: Always
          args:
            - "pod"
            - "-lapp=mongo"
      containers:
        - name: usercenter-backend
          image: registry.starcatmeow.cn/catmeow/catmeow-auth-service/usercenter-backend:$CI_COMMIT_TAG
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - name: config
              mountPath: "/app/config"
              readOnly: true
            - name: secretkey
              mountPath: "/app/secret"
              readOnly: true
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-credential
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-credential
                  key: password
            - name: MONGO_HOST
              value: mongo-0.mongo,mongo-1.mongo,mongo-2.mongo
            - name: NODE_CONFIG_DIR
              value: /app/config:/app/secret
      volumes:
        - name: config
          configMap:
            name: configmap.backend.usercenter.starcatmeow.cn
        - name: secretkey
          secret:
            secretName: secretkeys.backend.usercenter.starcatmeow.cn
            defaultMode: 256
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: usercenter-backend
  ports:
    - port: 80
      targetPort: 80
