apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap.backend.usercenter.starcatmeow.cn
data:
  production.yml: |
    listen_addr: 0.0.0.0
    listen_port: 80
    frontendurl: 'https://usercenter.starcatmeow.cn'
    auth:
      oidcurl: 'https://openid.starcatmeow.cn'
    jwt:
      tokenexpire: '1h'
    sitename: 'Catmeow 用户中心'
  custom-environment-variables.yml: |
    mongo:
      host: MONGO_HOST
      user: MONGO_USER
      password: MONGO_PASSWORD
