build_openid:
  before_script:
    - cd $CI_PROJECT_DIR/openid
  stage: build
  image: node:14
  script:
    - yarn install --cache-folder .yarn
    - npx gulp build copyejs
  artifacts:
    paths:
      - openid/dist
    expire_in: 30 days

pack_openid:
  before_script:
    - cd $CI_PROJECT_DIR/openid
  stage: pack
  needs:
    - build_openid
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/openid --dockerfile $CI_PROJECT_DIR/openid/Dockerfile --destination $CI_REGISTRY_IMAGE/openid:$CI_COMMIT_TAG --cache=true
  rules:
    - if: $CI_COMMIT_TAG