stages:
  - build
  - pack

build_usercenter_backend:
  stage: build
  image: node:14
  script:
    - yarn install
    - gulp build
  artifacts:
    paths:
      - dist
    expire_in: 30 days

pack_usercenter_backend:
  stage: pack
  needs:
    - build_usercenter_backend
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG