build_usercenter_backend:
  before_script:
    - cd $CI_PROJECT_DIR/usercenter_backend
  stage: build
  image: node:14
  script:
    - yarn install --cache-folder .yarn
    - npx gulp build
  artifacts:
    paths:
      - usercenter_backend/dist
    expire_in: 30 days

pack_usercenter_backend:
  before_script:
    - cd $CI_PROJECT_DIR/usercenter_backend
  stage: pack
  needs:
    - build_usercenter_backend
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/usercenter_backend --dockerfile $CI_PROJECT_DIR/usercenter_backend/Dockerfile --destination $CI_REGISTRY_IMAGE/usercenter-backend:$CI_COMMIT_TAG --cache=true
  rules:
    - if: $CI_COMMIT_TAG