before_script:
  - cd $CI_PROJECT_DIR/usercenter_frontend

stages:
  - build

build_usercenter_frontend:
  stage: build
  image: node:14
  script:
    - yarn install
    - NODE_ENV=production yarn build
  artifacts:
    paths:
      - usercenter_frontend/dist
    expire_in: 30 days